//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DeliveryServiceDBEntities2 : DbContext
    {
        private static DeliveryServiceDBEntities2 _context;
        public DeliveryServiceDBEntities2()
            : base("name=DeliveryServiceDBEntities2")
        {
        }
    
        public static DeliveryServiceDBEntities2 GetContext()
        {
            if (_context == null)
            {
                _context = new DeliveryServiceDBEntities2();
            }
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<EmployeeShift> EmployeeShifts { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<OrderStatu> OrderStatus { get; set; }
        public DbSet<PaymentMethod> PaymentMethods { get; set; }
        public DbSet<Shift> Shifts { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<UserRole> UserRoles { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UserStatu> UserStatus { get; set; }
    }
}
