//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public string Client { get; set; }
        public string AddressDelivery { get; set; }
        public Nullable<int> PaymentMethodID { get; set; }
        public Nullable<int> OrderDateTime { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public Nullable<int> CourierID { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual OrderStatu OrderStatu { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
